language: java
sudo: required
branches:
  only:
  - master
jdk:
- oraclejdk8
services:
- mongodb
script:
- mvn test -f NewsObserver/pom.xml
addons:
  ssh_known_hosts:
  - ec2-52-58-228-209.eu-central-1.compute.amazonaws.com
env:
  global:
    secure: ${super_secret_secure_from_website}
before_install:
-  echo $super_secret_password | gpg --batch --yes --passphrase-fd 0 BerkUbuntu.pem.gpg
-  chmod 400 BerkUbuntu.pem
after_success:
-  scp -i "BerkUbuntu.pem" -r NewsObserver/target/jarar ubuntu@ec2-52-58-228-209.eu-central-1.compute.amazonaws.com:~/.
-  chmod -x sshconnector.sh
-  sh sshconnector.sh
